### ISSUE TITLE
Release v1.3.0 causes "invalid truth value"

### ISSUE THREAD

**Issue by jacob-pro** [snok/container-retention-policy#13]
Version 1.3.0 has unfortunately caused my workflows to stop working, rolling back to 1.2.1 it works again:

```
Run snok/container-retention-policy@v1
  with:
    image-names: certbot-haproxy
    cut-off: 0 min ago UTC
    untagged-only: true
    account-type: personal
    token: ***
    timestamp-to-use: updated_at
    keep-at-least: 0
```

```
Traceback (most recent call last):
  File "/main.py", line 341, in <module>
    asyncio.run(main(*argv[1:]))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/main.py", line 329, in main
    inputs: Inputs = validate_inputs(
  File "/main.py", line 265, in validate_inputs
    filter_include_untagged_ = strtobool(filter_include_untagged) == 1
  File "/usr/local/lib/python3.10/distutils/util.py", line 321, in strtobool
    raise ValueError("invalid truth value %r" % (val,))
ValueError: invalid truth value ''
```

**Comment by sondrelg** [comment]
@Emilgardis do you have time to investigate? 🙂

**Comment by sondrelg** [comment]
Tested in my projects, and seems back to normal. Please let me know if this is not the case @jacob-pro. Thanks for reporting the issue!

**Comment by jacob-pro** [comment]
Thanks seems to be fixed now
