### ISSUE TITLE
Error: regex._regex_core.error: bad escape \d at position 7

### ISSUE THREAD

**Issue by Ks89** [snok/container-retention-policy#26]
Hello, I'm trying to cleanup my containers called "MY_IMAGE/windows" and "MY_IMAGE/unix".

This is my yaml:

```
name: Delete old container

on:
  schedule:
    - cron: '* 15 * * *' 
  workflow_dispatch:

jobs:
  clean-ghcr:
    name: Delete old unused container images
    runs-on: ubuntu-latest
    steps:
      - name: Delete containers
        uses: snok/container-retention-policy@v1
        with:
          image-names: MY_IMAGE/windows, MY_IMAGE/unix
          cut-off: A week ago UTC
          account-type: org
          org-name: MY_ORG
          keep-at-least: 1
          skip-tags: master,v*
          token: MY_TOKEN
```

It returns an error. This is the result:

```
run snok/container-retention-policy@v1
  with:
    image-names: MY_IMAGE/windows, MY_IMAGE/unix
    cut-off: 1 week ago UTC
    account-type: org
    org-name: MY_ORG
    keep-at-least: 1
    skip-tags: master,v*
    token:  ***
    timestamp-to-use: updated_at
    untagged-only: false
    filter-include-untagged: true

(...)

Traceback (most recent call last):
  File "/main.py", line 421, in <module>
    asyncio.run(main(*argv[1:]))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/main.py", line 375, in main
    inputs = Inputs(
  File "pydantic/main.py", line 329, in pydantic.main.BaseModel.__init__
    
  File "pydantic/main.py", line 1022, in pydantic.main.validate_model
  File "pydantic/fields.py", line 837, in pydantic.fields.ModelField.validate
  File "pydantic/fields.py", line 1118, in pydantic.fields.ModelField._apply_validators
  File "pydantic/class_validators.py", line 280, in pydantic.class_validators._generic_validator_cls.lambda3
  File "/main.py", line 231, in parse_human_readable_datetime
    parsed_cutoff = parse(v)
  File "/usr/local/lib/python3.10/site-packages/dateparser/conf.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/dateparser/__init__.py", line 61, in parse
    data = parser.get_date_data(date_string, date_formats)
  File "/usr/local/lib/python3.10/site-packages/dateparser/date.py", line 428, in get_date_data
    parsed_date = _DateLocaleParser.parse(
  File "/usr/local/lib/python3.10/site-packages/dateparser/date.py", line 178, in parse
    return instance._parse()
  File "/usr/local/lib/python3.10/site-packages/dateparser/date.py", line 182, in _parse
    date_data = self._parsers[parser_name]()
  File "/usr/local/lib/python3.10/site-packages/dateparser/date.py", line 196, in _try_freshness_parser
    return freshness_date_parser.get_date_data(self._get_translated_date(), self._settings)
  File "/usr/local/lib/python3.10/site-packages/dateparser/date.py", line 234, in _get_translated_date
    self._translated_date = self.locale.translate(
  File "/usr/local/lib/python3.10/site-packages/dateparser/languages/locale.py", line 131, in translate
    relative_translations = self._get_relative_translations(settings=settings)
  File "/usr/local/lib/python3.10/site-packages/dateparser/languages/locale.py", line 158, in _get_relative_translations
    self._generate_relative_translations(normalize=True))
  File "/usr/local/lib/python3.10/site-packages/dateparser/languages/locale.py", line 172, in _generate_relative_translations
    pattern = DIGIT_GROUP_PATTERN.sub(r'?P<n>\d+', pattern)
  File "/usr/local/lib/python3.10/site-packages/regex/regex.py", line 700, in _compile_replacement_helper
    is_group, items = _compile_replacement(source, pattern, is_unicode)
  File "/usr/local/lib/python3.10/site-packages/regex/_regex_core.py", line 1736, in _compile_replacement
    raise error("bad escape \\%s" % ch, source.string, source.pos)
regex._regex_core.error: bad escape \d at position 7
```

**Comment by jrdnrc** [comment]
Hello, I think I am having the same issue.

I've found a StackOverflow post indicating a regex library was updated which dateparser uses, and it does not pin a version.

https://stackoverflow.com/a/71501074

I hope this helps, it's been bugging me all day! Unfortunately, I know nothing about python otherwise I'd pop in a PR attempting to fix it.

Thanks for your work @sondrelg

**Comment by sondrelg** [comment]
We should be able to resolve it by pinning it in the dockerfile, but I'm away for a few hours, so maybe it will be resolved downstream by then 👍 

Either way sounds like we should probably also pin the 3 packages installed to limit the risk of similar things happening the future (even though it sounds unavoidable in this case).

**Comment by sondrelg** [comment]
I tested `v1` after releasing v1.4.1, and it seems to be fixed 👍 Please let me know if it doesn't work for you

**Comment by Ks89** [comment]
It's working now. thank you.

**Comment by jrdnrc** [comment]
Thank you @sondrelg !
