### ISSUE TITLE
RuntimeError: The connection pool was closed while 29 HTTP requests/responses were still in-flight.

### ISSUE THREAD

**Issue by andygrunwald** [snok/container-retention-policy#29]
## The situation

A registry with ~100 images.
Oldest one is ~1 year.

![Screenshot from 2022-03-19 17-57-35](https://user-images.githubusercontent.com/320064/159130747-c7e2ab41-4290-4de3-97e6-0011aabe0695.png)

## Workflow configuration

```yaml
name: Delete old container images from GitHub registry

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight

jobs:
  clean-ghcr:
    name: Delete old unused container images
    runs-on: ubuntu-20.04

    steps:
      - name: Delete 'web-app' containers older than a week
        uses: snok/container-retention-policy@v1
        with:
          image-names: web-app
          cut-off: A week ago UTC
          account-type: org
          org-name: <ORG-NAME>
          keep-at-least: 5
          token: ${{ secrets.token_registry_cleanup }}
          filter-tags: sha-*
```

## First run

Triggered manually via workflow_dispatch.
The following error occurred:

```
Traceback (most recent call last):
Deleted old image: web-app:2894453
  File "/usr/local/lib/python3.10/site-packages/anyio/streams/tls.py", line 108, in _call_sslobject_method
    result = func(*args)
  File "/usr/local/lib/python3.10/ssl.py", line 916, in read
    v = self._sslobj.read(len)
ssl.SSLWantReadError: The operation did not complete (read) (_ssl.c:2536)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 31, in read
    return await self._stream.receive(max_bytes=max_bytes)
  File "/usr/local/lib/python3.10/site-packages/anyio/streams/tls.py", line 171, in receive
Deleted old image: web-app:2203658
Deleted old image: web-app:2203593
Deleted old image: web-app:2203838
Deleted old image: web-app:2893511
Deleted old image: web-app:7090306
Deleted old image: web-app:2317312
Deleted old image: web-app:2893095
Deleted old image: web-app:2050005
Deleted old image: web-app:2219117
Deleted old image: web-app:2494134
Deleted old image: web-app:2134513
Deleted old image: web-app:8153032
Deleted old image: web-app:2720525
Deleted old image: web-app:2182005
Deleted old image: web-app:2134190
Deleted old image: web-app:2317320
Deleted old image: web-app:2049943
Deleted old image: web-app:2557148
Deleted old image: web-app:2893393
Deleted old image: web-app:13007727
Deleted old image: web-app:2203584
Deleted old image: web-app:2326200
Deleted old image: web-app:2698342
Deleted old image: web-app:2260291
Deleted old image: web-app:2893318
Deleted old image: web-app:2202288
Deleted old image: web-app:2556273
Deleted old image: web-app:2309113
Deleted old image: web-app:2203447
Deleted old image: web-app:2134701
Deleted old image: web-app:2556650
Deleted old image: web-app:2203149
Deleted old image: web-app:2049685
Deleted old image: web-app:2107640
Deleted old image: web-app:2164908
Deleted old image: web-app:2301283
Deleted old image: web-app:2556446
Deleted old image: web-app:2556268
Deleted old image: web-app:1973093
Deleted old image: web-app:2796721
Deleted old image: web-app:10068707
Deleted old image: web-app:2797230
Deleted old image: web-app:2221633
Deleted old image: web-app:2697653
Deleted old image: web-app:2705564
Deleted old image: web-app:2309083
Deleted old image: web-app:2598866
Deleted old image: web-app:2049789
Deleted old image: web-app:1973022
Deleted old image: web-app:1970603
Deleted old image: web-app:1971787
Deleted old image: web-app:1971219
Deleted old image: web-app:1969794
Deleted old image: web-app:1969813
Deleted old image: web-app:1901818
Deleted old image: web-app:1863482
Deleted old image: web-app:1896842
Deleted old image: web-app:1835569
Deleted old image: web-app:1969737
Deleted old image: web-app:1898563
Deleted old image: web-app:1969610
Deleted old image: web-app:1859709
Deleted old image: web-app:1629498
    data = await self._call_sslobject_method(self._ssl_object.read, max_bytes)
  File "/usr/local/lib/python3.10/site-packages/anyio/streams/tls.py", line 115, in _call_sslobject_method
    data = await self.transport_stream.receive()
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 1105, in receive
    await self._protocol.read_event.wait()
  File "/usr/local/lib/python3.10/asyncio/locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 8, in map_exceptions
    yield
  File "/usr/local/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 29, in read
    with anyio.fail_after(timeout):
  File "/usr/local/lib/python3.10/site-packages/anyio/_core/_tasks.py", line 103, in __exit__
    raise TimeoutError
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
    raise exc
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection.py", line 90, in handle_async_request
    return await self._connection.handle_async_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/http11.py", line 102, in handle_async_request
    raise exc
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/http11.py", line 81, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/http11.py", line 143, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/http11.py", line 172, in _receive_event
    data = await self._network_stream.read(
  File "/usr/local/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 28, in read
    with map_exceptions(exc_map):
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc)
httpcore.ReadTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/main.py", line 394, in main
    await asyncio.gather(*tasks)
  File "/main.py", line 333, in get_and_delete_old_versions
    await asyncio.gather(*tasks)
  File "/main.py", line 185, in delete_package
    return await delete_org_package_versions(
  File "/main.py", line 130, in delete_org_package_versions
    response = await http_client.delete(url)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1927, in delete
    return await self.request(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1506, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1593, in send
    response = await self._send_handling_auth(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1621, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1658, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1695, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 352, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/main.py", line 421, in <module>
    asyncio.run(main(*argv[1:]))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/main.py", line 387, in main
    async with AsyncClient(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1975, in __aexit__
    await self._transport.__aexit__(exc_type, exc_value, traceback)
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 332, in __aexit__
    await self._pool.__aexit__(exc_type, exc_value, traceback)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 326, in __aexit__
    await self.aclose()
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 312, in aclose
    raise RuntimeError(
RuntimeError: The connection pool was closed while 29 HTTP requests/responses were still in-flight.
```

## Result

The job failed, but it deleted the old images:

![Screenshot from 2022-03-19 18-02-45](https://user-images.githubusercontent.com/320064/159130921-843c8de8-bd27-43b0-994b-4c50e08acf6f.png)

A second manual trigger of the job ran successful and deleted 1 image.
The end result of two runs are: 5 images left, like configured.

**Comment by sondrelg** [comment]
The way I understand it, one of the requests return an error, causing the `asyncio.gather` call to aexit early. I think we could return exceptions like this

```diff
- await asyncio.gather(*tasks)
+ results = await asyncio.gather(*tasks, return_exceptions=True)
+ # check results
```

[here](https://github.com/snok/container-retention-policy/blob/main/main.py#L333).

Don't think we can get rid of the underlying httpx error easily. but it would get rid of this long confusing traceback.

**Comment by lerdt** [comment]
We've got the same error. Our configuration looks very similar to andygrunwald's. The versions to be deleted are also completely cleaned up, the second run is then error-free.

I also tested it with a package that had only 6 versions. Of these, 5 should remain and 1 should be deleted. This also led to the previously mentioned error in the first iteration.
Could it still have something to do with the timeout error from #18?

Thanks in advanced!

**Comment by sondrelg** [comment]
Not sure, but we can start by collecting and propagating HTTP errors properly, then I think the issue will become easier to debug. I'll try to do that this weekend if time permits.

Either way, it seems like things are working correctly. The images that are meant to be deleted are deleted, and images that should be untouched are untouched, correct? 🙂

**Comment by lerdt** [comment]
Thanks for the quick reply! This sounds good and no hurry at all. :)

Currently I have configured the action so that the dependencies of the individual steps no longer apply. The individual jobs are now executed parallel and independently of each other. This will still (often) result in an failing workflow, but it will **always** delete all specified versions of each package. So it works correctly and as expected.

**Comment by sondrelg** [comment]
@lerdt I just released v1.4.2 which should resolve the error dumps. If you were consistently seeing these, could you please verify whether the new release works well or not? 🙂  Hard to test this particular issue without prod data.

**Comment by lerdt** [comment]
Good morning @sondrelg and thanks for the reply / new version!

I've tested the new version (v1.4.2) and can confirm that the workflow now no longer leads to the described error. All desired versions will still be deleted. The long stack trace which described the timeout error is no longer visible. Only the message `Request to delete <package_name> timed out with error` is displayed.

For my use case this is completely sufficient - thank you!

**Comment by sondrelg** [comment]
Thanks for reporting and testing 👏
