### ISSUE TITLE
Error when action trigger is set on schedule 

### ISSUE THREAD

**Issue by jesusplanas** [snok/container-retention-policy#31]
Hi! I'm doing some tests with the action and I'm facing a very weird behavior. Every time that I put the action trigger to workflow_dispatch, it works as expected, but when I change it to on_schedule always fail in all repositories. Is the same action with different trigger and I don't know why it's happening. Here I attach the error log that I see in the action output and also my action definition: 
``` Run snok/container-retention-policy@v1.4.2
  with:
    cut-off: One month ago UTC
    account-type: org
    org-name: ********
    keep-at-least: 10
    filter-tags: *-rc*
    timestamp-to-use: created_at
    token: ***
    untagged-only: false
    filter-include-untagged: true
/usr/bin/docker run --name bcf0944ce007ac7804352b8d5f06414b6b331_04d39e --label 2bcf09 --workdir /github/workspace --rm -e INPUT_IMAGE-NAMES -e INPUT_CUT-OFF -e INPUT_ACCOUNT-TYPE -e INPUT_ORG-NAME -e INPUT_KEEP-AT-LEAST -e INPUT_FILTER-TAGS -e INPUT_TIMESTAMP-TO-USE -e INPUT_TOKEN -e INPUT_UNTAGGED-ONLY -e INPUT_SKIP-TAGS -e INPUT_FILTER-INCLUDE-UNTAGGED -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/benki/benki":"/github/workspace" ****************************  "org" "***************" "" "created_at" "One month ago UTC" "***" "false" "" "10" "*-rc*" "true"
Traceback (most recent call last):
  File "/main.py", line 433, in <module>
    asyncio.run(main(*argv[1:]))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/main.py", line 406, in main
    await asyncio.gather(*tasks)
  File "/main.py", line 254, in get_and_delete_old_versions
    versions = await GithubAPI.list_package_versions(
  File "/main.py", line 172, in list_package_versions
    return await list_org_package_versions(org_name=org_name, image_name=image_name, http_client=http_client)
  File "/main.py", line 78, in list_org_package_versions
    response.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/httpx/_models.py", line 1510, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '404 Not Found' for url 'https://api.github.com/orgs/*******/packages/container//versions?per_page=100'
For more information check: https://httpstatuses.com/404 

######## Action:
name: "Cleanup GHCR content"

on:
  schedule:
    - cron: '0 7 * * *'

jobs:
  purge-image:
    name: Delete image from ghcr.io
    runs-on: ubuntu-latest
    steps:

      - name: Delete 'rc' containers
        uses: snok/container-retention-policy@v1.4.2
        with:
          image-names: ${{ github.event.repository.name }}
          cut-off: One month ago UTC
          account-type: org
          org-name: myOrgName
          keep-at-least: 10
          filter-tags: '*-rc*'
          timestamp-to-use: created_at
          token: ${{ secrets.GH_DOCKERREGISTRY_TOKEN }}

**Comment by sondrelg** [comment]
This URL:
```
https://api.github.com/orgs/world-mobile-labs-ukraine/packages/container//versions?per_page=100
```

Should be 

```
https://api.github.com/orgs/world-mobile-labs-ukraine/packages/container/{image-name}/versions?per_page=100
```

Is `${{ github.event.repository.name }}` evaluating to an empty string?

**Comment by jesusplanas** [comment]
When I execute it manually it works, so it gets a value from `${{ github.event.repository.name }}`, the problem is when is scheduled the trigger, that seems that is not taken the variable value as is doing with the manual run, very weird. Here is the output of a manual run, as you can see the image name is retrieved correctly: 
``` [1](https://github.com/World-Mobile-Labs-Ukraine/benki/runs/5834302511?check_suite_focus=true#step:3:1)s
Run snok/container-retention-policy@v1.4.[2](https://github.com/World-Mobile-Labs-Ukraine/benki/runs/5834302511?check_suite_focus=true#step:3:2)
  with:
    image-names: benki
    cut-off: One month ago UTC
    account-type: org
    org-name: world-mobile-labs-ukraine
    keep-at-least: 10
    filter-tags: *-rc*
    timestamp-to-use: created_at
    token: ***
    untagged-only: false
    filter-include-untagged: true
/usr/bin/docker run --name bcf0977760a[3](https://github.com/World-Mobile-Labs-Ukraine/benki/runs/5834302511?check_suite_focus=true#step:3:3)1ae[4](https://github.com/World-Mobile-Labs-Ukraine/benki/runs/5834302511?check_suite_focus=true#step:3:4)b4ef09d48bf2892f7[5](https://github.com/World-Mobile-Labs-Ukraine/benki/runs/5834302511?check_suite_focus=true#step:3:5)091_a5[6](https://github.com/World-Mobile-Labs-Ukraine/benki/runs/5834302511?check_suite_focus=true#step:3:6)13d --label 2bcf09 --workdir /github/workspace --rm -e INPUT_IMAGE-NAMES -e INPUT_CUT-OFF -e INPUT_ACCOUNT-TYPE -e INPUT_ORG-NAME -e INPUT_KEEP-AT-LEAST -e INPUT_FILTER-TAGS -e INPUT_TIMESTAMP-TO-USE -e INPUT_TOKEN -e INPUT_UNTAGGED-ONLY -e INPUT_SKIP-TAGS -e INPUT_FILTER-INCLUDE-UNTAGGED -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/benki/benki":"/github/workspace" 2bcf09:[7](https://github.com/World-Mobile-Labs-Ukraine/benki/runs/5834302511?check_suite_focus=true#step:3:7)7760a31ae4b4ef09d4[8](https://github.com/World-Mobile-Labs-Ukraine/benki/runs/5834302511?check_suite_focus=true#step:3:8)bf28[9](https://github.com/World-Mobile-Labs-Ukraine/benki/runs/5834302511?check_suite_focus=true#step:3:9)2f75091  "org" "world-mobile-labs-ukraine" "benki" "created_at" "One month ago UTC" "***" "false" "" "[10](https://github.com/World-Mobile-Labs-Ukraine/benki/runs/5834302511?check_suite_focus=true#step:3:10)" "*-rc*" "true"
No more versions to delete for benki

**Comment by sondrelg** [comment]
Is there a reason why you cannot hardcode the name? Are you storing the workflow in a .github org-repo? 

Either way, this seems like it might be a general Github actions issue, rather than specific to this action 🙂

**Comment by jesusplanas** [comment]
I was using this variable as it is easy to move the action around all the repositories without changing any thing, but I'm going to test it hardcoding the image name in each action and lets see if it works as expected.
Thanks for the support!

**Comment by sondrelg** [comment]
Sounds good 👍  I definitely understand the motivation 🙂

**Comment by jesusplanas** [comment]
I have tested it hardcoding the image name and now works fine. Thanks!
