### ISSUE TITLE
pydantic.error_wrappers.ValidationError: 1 validation error for Inputs cut_off   Unable to parse ''

### ISSUE THREAD

**Issue by scottgigante-immunai** [snok/container-retention-policy#50]
Hi! I'm hitting a validation error when using this action.

```
Traceback (most recent call last):
  File "/main.py", line 513, in <module>
    asyncio.run(main(*argv[1:]))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/main.py", line 456, in main
    inputs = Inputs(
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
    continue
pydantic.error_wrappers.ValidationError: 1 validation error for Inputs
cut_off
  Unable to parse '' (type=value_error)
```

Details at https://github.com/scottgigante-immunai/openproblems/actions/runs/3466497170/jobs/5790658827#step:3:14

**Comment by sondrelg** [comment]
Here you go :slightly_smiling_face:  https://github.com/snok/container-retention-policy/blob/main/action.yml#L23

**Comment by scottgigante-immunai** [comment]
Thanks for the quick response and sorry for the noise!
